site_name: Microsoft O365 MITRE ATT&CK Detections using Splunk
theme:
  name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
nav:
  - Overview: 'index.md'
  - Account created - T1136: 'CreateAccount-T1136.md'
  - Administrator role assigned [T1098.003] : 'AccountManipulationAdditionalCloudRoles-T1098-003.md'