site_name: Microsoft O365 MITRE ATT&CK Detections using Splunk
theme:
  name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
nav:
  - Overview: 'index.md'
  - CreateAccount-T1136: 'CreateAccount-T1136.md'