site_name: Ashish Gupta
theme:
  name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
nav:
- Index: 'index.md'
- Overview: 'SANS Holiday Hack Challenge 2021/index.md'
- Kringlecon Orientation: 'SANS Holiday Hack Challenge 2021/KringleconOrientation.md'
- Where in the world is Carmel Santaigo: 'SANS Holiday Hack Challenge 2021/Where in the world is Carmel Santaigo.md'
- Thaw Frost Tower Entrance: 'SANS Holiday Hack Challenge 2021/Thaw Frost Tower Entrance.md'
- Slot Machine Investigation: 'SANS Holiday Hack Challenge 2021/Slot Machine Investigation.md'
- Thaw Frost Tower Entrance: 'SANS Holiday Hack Challenge 2021/Thaw Frost Tower Entrance.md'
- Strange USB Device: 'SANS Holiday Hack Challenge 2021/Strange USB device.md'
- Shell Code Primer: 'SANS Holiday Hack Challenge 2021/Shell Code Primer.md'
- Printer Exploitation: 'SANS Holiday Hack Challenge 2021/Printer Exploitation.md'
- Kerberoasting on an Open Fire: 'SANS Holiday Hack Challenge 2021/Kerberoasting on an Open Fire.md'
- Splunk: 'SANS Holiday Hack Challenge 2021/Splunk.md'
- Now Hiring: 'SANS Holiday Hack Challenge 2021/Now Hiring.md'
- Customer Complaint Analysis: 'SANS Holiday Hack Challenge 2021/Customer Complaint Analysis.md'
- Frost Tower Website Checkup: 'SANS Holiday Hack Challenge 2021/Frost Tower Website Checkup.md'
- FPGA Programming: 'SANS Holiday Hack Challenge 2021/FPGA Programming.md'