site_name: Microsoft O365 Security Implementation
theme:
  name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
nav:
- Overview: 'index.md'
- Setup AzureAD App For Splunk: 'SetupAzureADAppForSplunk.md'
- Set Tenant Properties: 'SetupTenantProperties.md'
- Disable Security Defaults: 'DisableSecurityDefaults.md'
- Create Emergency User: 'CreateEmergencyUser.md'
- Implement MFA: 'ImplementMFA.md'
- Block OFAC Countries: 'BlockOFACCountries.md'
- Disable basic authentication: 'DisableBasicAuth.md'
- Restrict External Collaboration: 'RestrictExtarnelCollaboration.md'
- Restrict User Settings: 'RestrictUserSettings.md'
- Block Misc Azure Services for non-admin users: 'BlockMiscAzureServices.md'
- Detections:
  - User Added to administrator role: Detection-UserAddedToAdminRole.md
  - Cloud only account created: Detection-CloudOnlyAccountCreated.md
- The main blog: "http://guptaashish.com"