site_name: Microsoft O365 Security Implementation
theme:
  name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
nav:
- Overview: 'index.md'
- Setup AzureAD App For Splunk: 'SetupAzureADAppForSplunk.md'
- Create Emergency User: 'CreateEmergencyUser.md'
- Implement MFA: 'ImplementMFA.md'
- Block OFAC Countries: 'BlockOFACCountries.md'
- Restrict Extarnel Collaboration: 'RestrictExtarnelCollaboration.md'
- Enable Self Service Password Reset: 'EnableSelfServicePasswordReset.md'
