site_name: Microsoft O365 Security Implementation
theme:
  name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
nav:
- Overview: '/site/index.md'
- Setup AzureAD App For Splunk: '/blog/site/O365SecurityImplementation/site/SetupAzureADAppForSplunk/index.html'
- Crete Emergency User: '/site/CreateEmergencyUser/index.html'
- Implement MFA: '/site/ImplementMFA/index.html'
- Block OFAC Countries: '/site/BlockOFACCountries/index.html'
- Restrict Extarnel Collaboration: '/site/RestrictExtarnelCollaboration/index.html'
- Enable Self Service Password Reset: '/site/EnableSelfServicePasswordReset/index.html'
