site_name: SANS Holiday Hack Challenge 2022 Kringlecon V Golden Rings
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
  palette:
    accent: red
    primary: indigo
  
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
- Overview: 'index.md'
- Answers/high level approach: 'AnswersToObjectives.md'
- Kringlecon Orientation: 'KringleconOrientation.md'
- Wandering around the north pole: WanderingAroundTheNorthPole.md
- Tolkien Ring:
  - Wireshark Phishing: TolkienRing/WiresharkPhishing.md
  - Windows Event Logs: TolkienRing/WindowsEventLogs.md
  - Suricata Regatta: TolkienRing/SuricataRegatta.md
- Elfen Ring:
  - Clone with a difference: ElfenRing/CloneWithaDifference.md
  - Prison Escape: ElfenRing/PrisonEscape.md
  - Jolly CI/CD: ElfenRing/JollyCICD.md
- Web Ring:
  - Naughty IP: WebRing/NaughtyIP.md
  - Credential Mining: WebRing/CredentialMining.md
  - 404 FTW: WebRing/404FTW.md
  - IMDS, XXE and other abbreviations: WebRing/IMDSandXXE.md
  - Open Boria Mine Door: WebRing/OpenBoriaMineDoor.md
  - Glamtariel’s Fountain: WebRing/GlamtarielsFountain.md
- Cloud Ring:
  - AWS CLI Intro: CloudRing/AWSCLIIntro.md
  - TrufflehogSearch: CloudRing/TrufflehogSearch.md
  - Exploitation via AWS CLI: CloudRing/ExploitationViaAWSCLI.md
- Burning Ring of Fire:
  - Buy a hat: BurningRingOfFire/BuyaHat.md
  - Blockchain Divination: BurningRingOfFire/BlockchainDivination.md
  - Exploit a smart contract: BurningRingOfFire/ExploitaSmartContract.md
- Returning the rings to Santa: ReturningRingsToSanta.md
- Conclusion: Conclusion.md
- CyberSecurity Learnings: CyberSecurityLearnings.md
- Thank you: ThankYou.md
- Main Blog : https://guptaashish.com